<div class="interne_scores">
[accordion]
[toggle title="Stand na ronde ${name}" state="closed"]
    <#include "/rankingGroup.ftlh">
[/toggle]
[toggle title="Ronde resultaten" state="closed"]
    <#include "/roundResult.ftlh">
[/toggle]
[toggle title="Ronde overzicht" state="closed"]
    <#include "/roundList.ftlh">
[/toggle]
[toggle title="Competitie overzicht" state="closed"]
    <#include "/competitionList.ftlh">
[/toggle]
[/accordion]
</div>
